### ISSUE TITLE
"What can I search for you ?" repeating again and again.

### ISSUE THREAD

**Issue by Shekharrajak** [vaibhawvipul/WikipediaForBlinds#1]
After I logged in .I found that it is saying "What can I search for you ?" repeatedly and reloading the same page again and again.

**Comment by vaibhawvipul** [comment]
Hey, shekhar! Yeah there are problems, if you search a term which is not available on wikipedia, it keeps on asking you for the current term. Like, if you search "Python" It won't return any result but If you search "Python(Programming Language)" it renders back result. That how wiki's api works. I am trying to improve the algorithm more.

**Comment by Shekharrajak** [comment]
Wow great! please try to write how to setup and requirement.txt in  readme.md  file.

**Comment by vaibhawvipul** [comment]
setup? you just need to start a django project.
